---
- name: install php container app
  sudo: yes
  docker:
    name: php
    image: nolabs/php
    state: started
    ports:
      - "9000:9000"
    links:
      - mysql
    volumes:
      - /var/deployments/badges-io/releases/1:/var/deployments/badges-io/releases/1

- name: config badges-io-dev site
  sudo: yes
  shell: docker cp /var/deployments/badges-io/releases/1/environment/devel/provision/ansible/templates/php/conf/php-fpm.conf php:/usr/local/etc

- name: config php.ini
  sudo: yes
  shell: docker cp /var/deployments/badges-io/releases/1/environment/devel/provision/ansible/templates/php/conf/php.ini php:/usr/local/etc/php

- name: restart php container
  sudo: yes
  shell: docker restart php