Infrastructure\Resource\Api\Domain\Entity\Image\ImageApiResource:
    exclusion_policy: ALL
    xml_root_name: image

    properties:
        id:
            expose: true
            type: string

        name:
            expose: true
            type: string
        
        width:
            expose: true
            type: integer

        height:
            expose: true
            type: integer

        format:
            expose: true
            type: string

        href:
            expose: true
            type: string