Infrastructure\Resource\Api\Domain\Entity\User\UserApiResource:
    exclusion_policy: ALL
    xml_root_name: user

    properties:
        id:
            expose: true
            type: string

        username:
            expose: true
            type: string

        email:
            expose: true
            type: string

    relations:
        -
            rel: login
            title: Login into the system
            href:
                route: put_user_login
                absolute: true

        -
            rel: signin
            title: Sign in to the system
            href:
                route: put_user_sign_in
                absolute: true