Infrastructure\Resource\Api\Domain\Entity\User\UserApiResource:
    exclusion_policy: ALL
    xml_root_name: user

    properties:
        id:
            expose: true
            type: string
        username:
            expose: true
            type: string
        email:
            expose: true
            type: string