main:
    type: rest
    resource: "@GamificationCoreBundle/Resources/config/api-routes/gamification-api-routes.xml"
    prefix: api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc