Infrastructure\Resource\Domain\Entity\User\UserResource:
    exclusion_policy: ALL
    xml_root_name: user

    properties:
        id:
            expose: true
            type: string

        username:
            expose: true
            type: string

        email:
            expose: true
            type: string

    relations:
        -
            rel: login
            title: Login into the system
            href:
                route: put_user_login
                absolute: true

        -
            rel: signup
            title: Sign in to the system
            href:
                route: put_user_sign_up
                absolute: true

        -
            rel: list_badges
            title: Get the badges list by User Id
            href:
                route: get_badges_list
                absolute: true
                parameters:
                    userId: expr(object.id())

        -
            rel: create_badge
            title: Create a new badge
            href:
                route: post_badge_create
                absolute: true
