CREATE USER 'badgesUser'@'%%' IDENTIFIED BY 'badgesUser';
GRANT ALL PRIVILEGES ON *.* TO 'badgesUser'@'%%';
FLUSH PRIVILEGES;

/*CREATE TABLE Badge
(
 id VARCHAR(200) NOT NULL,
 name VARCHAR(50) NOT NULL,
 description VARCHAR(200) NOT NULL,
 isMultiTenant TINYINT(1) NOT NULL,
 imageId VARCHAR(200) DEFAULT NULL,
 userId VARCHAR(200) DEFAULT NULL,
 UNIQUE INDEX UNIQ_3F31671910F3034D (imageId),
 INDEX IDX_3F31671964B64DCC (userId),
 PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE Image
(
 id VARCHAR(200) NOT NULL,
 name VARCHAR(200) NOT NULL,
 width INT NOT NULL,
 height INT NOT NULL,
 format VARCHAR(5) NOT NULL,
 PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

CREATE TABLE User
(
 id VARCHAR(200) NOT NULL,
 email VARCHAR(50) NOT NULL,
 userName VARCHAR(50) NOT NULL,
 passWord VARCHAR(200) NOT NULL,
 PRIMARY KEY(id)
 ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB;

ALTER TABLE Badge ADD CONSTRAINT FK_3F31671910F3034D FOREIGN KEY (imageId) REFERENCES Image (id);
ALTER TABLE Badge ADD CONSTRAINT FK_3F31671964B64DCC FOREIGN KEY (userId) REFERENCES User (id);*/
