---
- name: install apache container app
  sudo: yes
  docker:
     name: apache
     image: httpd:latest
     state: started
     ports:
      #- "8443:8443"
      - "8080:80"
     links:
       - php
     volumes:
       - /var/deployments/badges-io/releases/1:/var/deployments/badges-io/releases/1

- name: copy ssl private key
  sudo: yes
  shell: docker cp /var/deployments/badges-io/releases/1/environment/devel/provision/ansible/templates/apache/key.pem apache:/usr/local/apache2

- name: copy ssl certificate
  sudo: yes
  shell: docker cp /var/deployments/badges-io/releases/1/environment/devel/provision/ansible/templates/apache/cert.pem apache:/usr/local/apache2

- name: config apache container
  sudo: yes
  shell: docker cp /var/deployments/badges-io/releases/1/environment/devel/provision/ansible/templates/apache/conf/httpd.conf apache:/usr/local/apache2/conf

- name: restart apache container
  sudo: yes
  shell: docker restart apache